// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkrxXMuiDDqL0deJ1YxM9F5WElFzL4hwQ',
    appId: '1:677597051611:web:046079cd7b572f4d232afe',
    messagingSenderId: '677597051611',
    projectId: 'chat-app-64cad',
    authDomain: 'chat-app-64cad.firebaseapp.com',
    storageBucket: 'chat-app-64cad.appspot.com',
    measurementId: 'G-STWWK10ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--1bUQ43g6r-SwbkCCtOol05oJW9Lics',
    appId: '1:677597051611:android:94a15d938cea1854232afe',
    messagingSenderId: '677597051611',
    projectId: 'chat-app-64cad',
    storageBucket: 'chat-app-64cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCDu5yT_6-NjdGIv5VJa1wZiSkadhIBI',
    appId: '1:677597051611:ios:c3422b8b46311072232afe',
    messagingSenderId: '677597051611',
    projectId: 'chat-app-64cad',
    storageBucket: 'chat-app-64cad.appspot.com',
    iosClientId: '677597051611-k65sov7p7uv3d7vundkkrnbdpbgvkpk8.apps.googleusercontent.com',
    iosBundleId: 'appitc.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVCDu5yT_6-NjdGIv5VJa1wZiSkadhIBI',
    appId: '1:677597051611:ios:143d967fa8f663cf232afe',
    messagingSenderId: '677597051611',
    projectId: 'chat-app-64cad',
    storageBucket: 'chat-app-64cad.appspot.com',
    iosClientId: '677597051611-t4i0kfbrd3jkm1e5g02553pm1dblish4.apps.googleusercontent.com',
    iosBundleId: 'appitc.chatApp.RunnerTests',
  );
}
